# Generated by Django 4.0 on 2022-01-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_remove_choice_question_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='question',
            field=models.ManyToManyField(to='onlinecourse.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=254),
        ),
    ]
